### ISSUE TITLE
Fehler während docker-compose up

### ISSUE THREAD

**Issue by Bernd1234-art** [MSG134/IVCT_Compositions#11]
Es wurde versucht das IVCT auf einem Windows 10 Pro Rechner mittels Docker Desktop zu installieren. Bei Eingabe des Befehls docker-compose up kommt folgender Fehler:

```
PS C:\IVCT_neu\IVCT_Operation-develop\IVCT_Operation-develop\pitch\bridge-network\ivct> docker-compose up
Pulling activemq (rmohr/activemq:5.14.5-alpine)...
Traceback (most recent call last):
  File "site-packages\docker\credentials\store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-credential-desktop.EXE', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages\docker\credentials\store.py", line 35, in get
  File "site-packages\docker\credentials\store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 361, in ensure_image_exists
  File "compose\service.py", line 1250, in pull
  File "compose\progress_stream.py", line 102, in get_digest_from_pull
  File "compose\service.py", line 1215, in _do_pull
  File "site-packages\docker\api\image.py", line 396, in pull
  File "site-packages\docker\auth.py", line 48, in get_config_header
  File "site-packages\docker\auth.py", line 324, in resolve_authconfig
  File "site-packages\docker\auth.py", line 235, in resolve_authconfig
  File "site-packages\docker\auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".')
[12660] Failed to execute script docker-compose
PS C:\IVCT_neu\IVCT_Operation-develop\IVCT_Operation-develop\pitch\bridge-network\ivct>
```

**Comment by rhzg** [comment]
can you please try to run `docker login`

This should give you something like that:

```
Authenticating with existing credentials...
Login Succeeded
```
If that has issues as well, have a look into that post (there are some suggestions to solve that issue): https://github.com/docker/docker-credential-helpers/issues/60

**Comment by Bernd1234-art** [comment]
#Solved
The error could be remedied by creating and logging on to the docker hub.
